# Generated by Django 5.1.7 on 2025-04-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='facebook_acount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
