# Generated by Django 5.1.7 on 2025-04-11 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_project_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='current_amount',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_featured',
        ),
    ]
